void uint32_to_str(char * str, uint32_t num);
uint8_t ReadCalibrationByte( uint8_t index );
void int_to_5digit(int num, char * buffer);
void int_to_4digit(int num, char * buffer);
void int_to_3digit(int num, char * buffer);
void int_to_4digit_nodec(int num, char * buffer);
void int_to_hex(char * str, int num);
void calc_crc8(can_frame_t *frame);
void calc_sum2(can_frame_t *frame);
void calc_checksum4(can_frame_t *frame);
void convert_5bc_to_array(volatile Leaf_2011_5BC_message * src, uint8_t * dest);
void convert_array_to_5bc(volatile Leaf_2011_5BC_message * dest, uint8_t * src);
void convert_5c0_to_array(volatile Leaf_2011_5C0_message * src, uint8_t * dest);